# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
target 'YemekKapimda' do
  # Comment the next line if you don't want to use dynamic frameworks
  
  use_frameworks!

  # Pods for YemekKapimda
    pod 'Alamofire', '~> 4.4'
    pod 'Kingfisher', '~> 5.15.8'

  target 'YemekKapimdaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YemekKapimdaUITests' do
    # Pods for testing
  end

end
